CREATE TABLE juego
(
Titulo VARCHAR2(20) CONSTRAINT JUE_TIT_PK PRIMARY KEY,
Pegi NUMBER(2),
codigo_juego CHAR(18) NOT NULL,
Genero VARCHAR2(20)
);

CREATE TABLE jugador
(
DNI CHAR(9) CONSTRAINT JUG_DNI_PK PRIMARY KEY,
Nombre VARCHAR2(20) NOT NULL,
Nick VARCHAR2(20) DEFAULT 'PLAYER_UNKNOW',
Edad NUMBER(2)CONSTRAINT JUG_EDA_CK CHECK(EDAD>16)
);

CREATE TABLE equipo
(
Nombre VARCHAR2(20) NOT NULL CONSTRAINT EQUI_NOM_UK UNIQUE,
Numero_Jugadores NUMBER(1) CONSTRAINT EQUI_NOM_NULL NOT NULL,
Jugador_lider CHAR(9) CONSTRAINT EQU_JUG_FK REFERENCES jugador,
Juego VARCHAR2(20),
CONSTRAINT equ_pri_pk PRIMARY KEY (Nombre, Juego),
CONSTRAINT EQU_JUE_FK FOREIGN KEY (Juego) REFERENCES juego
);
 
 ALTER TABLE jugador MODIFY (Edad NUMBER(3));
 ALTER TABLE equipo MODIFY (Numero_Jugadores NUMBER(2));
 ALTER TABLE equipo ADD (Ganadas NUMBER(3));
 ALTER TABLE equipo DISABLE CONSTRAINT EQU_JUG_FK;
 ALTER TABLE equipo DROP CONSTRAINT EQU_JUG_FK;
 ALTER TABLE equipo DROP COLUMN Jugador_lider;
 ALTER TABLE juego MODIFY (Pegi CONSTRAINT JUE_PEG_CK CHECK (Pegi>3));
 ALTER TABLE equipo ADD(Mejor_Jugador CHAR(9) CONSTRAINT EQU_MJUG_FK REFERENCES jugador);

 
 
 DROP TABLE equipo;
 DROP TABLE jugador;
 DROP TABLE juego;
 