------------------------------APARTADO A---------------------------- 
 CREATE TABLE CLIENTE 
   (	DNI CHAR(9), 
	NOMBRE VARCHAR2(30), 
	DIRECCION VARCHAR2(15), 
	TELEFONO NUMBER(9), 
	SALDO NUMBER(9,2) CONSTRAINT SAL_CLI_CK CHECK (saldo>0)
   ) ;
ALTER TABLE CLIENTE ADD CONSTRAINT CLI_DNI_PK PRIMARY KEY (DNI);

  CREATE TABLE PEDIDO 
   (	N_PEDIDO NUMBER(9), 
	FECHA DATE, 
	DNI CHAR(9) NOT NULL
   ) ;
ALTER TABLE PEDIDO ADD CONSTRAINT PED_NPE_PK PRIMARY KEY (N_PEDIDO);

  CREATE TABLE ARTICULO 
   (	N_ARTICULO NUMBER(9), 
	NOMBRE VARCHAR2(30)unique, 
	PRECIO_VENTA NUMBER(9), 
    ID_DEPARTAMENTO NUMBER(9)NOT NULL
   ) ;
ALTER TABLE ARTICULO ADD CONSTRAINT ART_NAR_PK PRIMARY KEY (N_ARTICULO);

  CREATE TABLE PEDIDO_ARTICULO 
   (	N_PEDIDO NUMBER(9), 
	N_ARTICULO NUMBER(9)NOT NULL, 
	CANTIDAD NUMBER(4)
   ) ;
ALTER TABLE PEDIDO_ARTICULO ADD CONSTRAINT PEAR_NUM_PK PRIMARY KEY (N_PEDIDO,N_ARTICULO);

  CREATE TABLE DEPARTAMENTO 
   (	ID_DEPARTAMENTO NUMBER(9), 
	AREA_VENTAS VARCHAR2(9)
   ) ;
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT DEP_ID_PK PRIMARY KEY (ID_DEPARTAMENTO);

  CREATE TABLE EMPLEADO 
   (	DNI CHAR(9), 
	NOMBRE VARCHAR2(30), 
	DIRECCION VARCHAR2(15), 
	TELEFONO NUMBER(9), 
	SALARIO NUMBER(9,2),
    ES_DIRECTOR CHAR(2),
    ID_DEPARTAMENTO NUMBER(9)NOT NULL
   ) ;
ALTER TABLE EMPLEADO ADD CONSTRAINT EMP_DNI_PK PRIMARY KEY (DNI);

  CREATE TABLE PROVEEDOR 
   (	CIF NUMBER(9), 
	NOMBRE VARCHAR(30)UNIQUE, 
	DIRECCION NUMBER(4),
    TELEFONO NUMBER(9)
   ) ;
ALTER TABLE PROVEEDOR ADD CONSTRAINT PRO_CIF_PK PRIMARY KEY (CIF);

CREATE TABLE PROVEEDOR_ARTICULO 
   (	CIF NUMBER(9)NOT NULL, 
	N_ARTICULO NUMBER(9)NOT NULL, 
	PRECIO_PROVEEDOR NUMBER(9)
   ) ;
ALTER TABLE PROVEEDOR_ARTICULO ADD CONSTRAINT PRAR_CIFN_PK PRIMARY KEY (CIF,N_ARTICULO);

ALTER TABLE PEDIDO ADD CONSTRAINT PED_DNI_FK FOREIGN KEY(DNI)REFERENCES CLIENTE(DNI);
ALTER TABLE ARTICULO ADD CONSTRAINT ART_DEP_FK FOREIGN KEY(ID_DEPARTAMENTO)REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO);
ALTER TABLE EMPLEADO ADD CONSTRAINT EMP_DEP_FK FOREIGN KEY(ID_DEPARTAMENTO)REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO);
ALTER TABLE PEDIDO_ARTICULO ADD CONSTRAINT PEAR_PED_FK FOREIGN KEY(N_PEDIDO)REFERENCES PEDIDO(N_PEDIDO);
ALTER TABLE PEDIDO_ARTICULO ADD CONSTRAINT PEAR_ART_FK FOREIGN KEY(N_ARTICULO)REFERENCES ARTICULO(N_ARTICULO);
ALTER TABLE PROVEEDOR_ARTICULO ADD CONSTRAINT PRAR_CIF_FK FOREIGN KEY(CIF)REFERENCES PROVEEDOR(CIF);
ALTER TABLE PROVEEDOR_ARTICULO ADD CONSTRAINT PRAR_ART_FK FOREIGN KEY(N_ARTICULO)REFERENCES ARTICULO(N_ARTICULO);

ALTER TABLE CLIENTE ADD CONSTRAINT CLI_SAL_CK CHECK (SALDO <0);
ALTER TABLE PEDIDO_ARTICULO ADD CONSTRAINT ART_CANT_CK CHECK (CANTIDAD BETWEEN 1 AND 30);

---------------------------APARTADO B------------------------
ALTER TABLE CLIENTE ADD APELLIDO VARCHAR2(20);
ALTER TABLE EMPLEADO ADD CONSTRAINT EMP_SAL_CK CHECK (SALARIO BETWEEN 800 AND 2000);
ALTER TABLE cliente disable constraint  SAL_CLI_CK;

---------------------------APARTADO C------------------------
CREATE INDEX CLI_NAP_IDX ON CLIENTE (NOMBRE,APELLIDO);


---------------------------APARTADO D------------------------


---------------------------APARTADO E------------------------
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE PEDIDO CASCADE CONSTRAINTS;
DROP TABLE ARTICULO CASCADE CONSTRAINTS;
DROP TABLE PEDIDO_ARTICULO CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR_ARTICULO CASCADE CONSTRAINTS;

DROP INDEX CLI_NAP_IDX;
DROP INDEX ART_NOM_IDX;




CREATE TABLE cliente(
DNI char(9) CONSTRAINT DNI_CLI_PK PRIMARY KEY, 
Nombre varchar2(100),
Apellido varchar2(100),
Direccion varchar2(100),
Telefono varchar2(12)
);


CREATE TABLE Pedido(
DNI varchar2(9), 
Precio number(10),
NPedido varchar2(100),
CONSTRAINT ID_PED_PK PRIMARY KEY (DNI, NPedido),
CONSTRAINT DNI_PED_PK FOREIGN KEY (DNI) REFERENCES cliente(DNI)
);

CREATE TABLE Articulo(
id_articulo varchar2(100) CONSTRAINT id_art_pk PRIMARY KEY,
nombre varchar2(100),
precio number(38)
);

CREATE TABLE Contiene(
id_pedido varchar2(100) , 
id_articulo varchar2(100),
CONSTRAINT id_ped_fk FOREIGN KEY (id_pedido) REFERENCES  pedido(NPedido),
CONSTRAINT id_art_fk  FOREIGN KEY (id_articulo) REFERENCES articulo(id_articulo), 
CONSTRAINT id_cont_pk PRIMARY KEY (ID_PEDIDO, ID_ARTICULO)



);









