--Ejercicio 1

CREATE TABLE Editorial(
codigo_editorial VARCHAR2(10) CONSTRAINT EDI_COD_PK PRIMARY KEY,
nombre VARCHAR2(40)NOT NULL
);

CREATE TABLE Autor(
codigo_autor VARCHAR2(10) CONSTRAINT AUT_COD_PK PRIMARY KEY,
nombre_autor VARCHAR2(40)NOT NULL CONSTRAINT AUT_NOM_UK UNIQUE
);

CREATE TABLE Libro
(
codigo_libro VARCHAR2(10) CONSTRAINT LIB_COD_PK PRIMARY KEY,
titulo VARCHAR2(40) CONSTRAINT LIB_TIT_UK UNIQUE, 
precio NUMBER(6,2)  DEFAULT 10 CONSTRAINT LIB_PRE_CK CHECK (precio BETWEEN 0 AND 100),
codigo_ed VARCHAR2(20) NOT NULL,
codigo_au VARCHAR2(20) CONSTRAINT AUT_COD_FK REFERENCES Autor,
CONSTRAINT COD_EDI_FK FOREIGN KEY (codigo_ed) REFERENCES Editorial
);

DROP TABLE Libro;

--Ejercicio2

CREATE TABLE Suministrador
(
Cod_S
Nom_S
Ciudad_s
Estado
);
CREATE TABLE Pieza
(

);
CREATE TABLE Cargamento
(

);
